version: '3.8'

services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5432
    expose:
      - 5432
    env_file:
      - .env

  app:
    container_name: app
    build:
      context: ../
    image: app
    ports:
      - 8001:8000
    env_file:
      - ../.env
    volumes:
      - .env:/usr/core/app/core/.env
    depends_on:
      - postgres


volumes:
  db-data:
    driver: local